apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - image: nginx:1.19
    name: mynginx
    volumeMounts:
    - mountPath: /test
      name: emptydir-test
  volumes:
  - name: emptydir-test
    emptyDir: {}