apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: myapp
  annotations:
    kubernetes.io/change-cause: deploy/mydeploy is set as mycontainer=clarusway/clarusweb:1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: mycontainer
        image: clarusway/clarusweb:1.0
        ports:
        - containerPort: 80